services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200 >/dev/null || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 30

  api:
    build: ./api
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
    ports:
      - "5080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
